In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
a = np.array(my_list)

In [4]:
a

array([1, 2, 3, 4])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
evens = np.arange(0,10,2)

In [9]:
evens

array([0, 2, 4, 6, 8])

In [10]:
lol = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(lol)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(matrix)

numpy.ndarray

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3)) # 1st number in tuple represents the rows and 2nd number represents the columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(1,4,4) # linspace() gives 'n' evenly spaced points between a given range (both inclusive)

array([1., 2., 3., 4.])

In [18]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [19]:
np.eye(4) #Identity Function

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5) # 1D array of 5 random numbers between 0 and 1

array([0.83596458, 0.2794642 , 0.55439611, 0.09828802, 0.05237122])

In [21]:
np.random.rand(3,3) # 2D array of random numbers consisting of 3 rows and 3 columns

array([[0.68403468, 0.69748686, 0.93913466],
       [0.961514  , 0.14621214, 0.77614941],
       [0.64908868, 0.68175326, 0.41356778]])

In [22]:
np.random.randn(4) #Return a sample from standard normal distribution

array([-1.30993399,  0.36219983,  0.38552685, -0.24661952])

In [23]:
np.random.randn(4,4)

array([[-1.84108741,  0.62657644,  1.39958056, -1.54999679],
       [-0.53072627,  0.85167854,  0.73873676,  0.8376377 ],
       [ 0.33405571, -0.50688271, -0.52962001, -1.40009999],
       [ 0.55943706, -0.05326273,  0.08063306,  0.64752848]])

In [24]:
# To get random numbers from a given range, we can use random.randint() function

In [25]:
np.random.randint(1,100) # Gives a random number between 1 to 100 (100 exclusive)

10

In [26]:
# If you want more than 1 random integer in a range, you can pass an additional argument to randint() function

In [27]:
np.random.randint(1,20,5)

array([ 8, 16, 13,  3, 11])

In [28]:
np.random.randint(1,10,15) # Here, array of 15 random numbers is generated in range 1 to 10. So, there must be repetitions.

array([7, 8, 9, 5, 1, 9, 2, 4, 1, 3, 8, 1, 8, 2, 6])

In [29]:
# We can also create an array using set as argument. Here, the properties of set are retained. So, duplicates are removed.
np.array({1,2,3,1,2,4,1})

array({1, 2, 3, 4}, dtype=object)

In [30]:
# It gives empty array as no numbers are there in range(-20,-11) using step of -2. So, condition holds false
np.arange(-20,-11,-2)

array([], dtype=int32)

In [31]:
np.arange(20,10,-2)

array([20, 18, 16, 14, 12])

In [32]:
# Unlike range() function, arange() function works with floats also for start, end and step size also
np.arange(0.1,10.99)

array([ 0.1,  1.1,  2.1,  3.1,  4.1,  5.1,  6.1,  7.1,  8.1,  9.1, 10.1])

In [33]:
np.arange(0.1,10.99,0.01)

array([ 0.1 ,  0.11,  0.12, ..., 10.96, 10.97, 10.98])

In [34]:
my_array = np.arange(1,26)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [35]:
# Using reshape() function, we can reshape a 1D array to matrix but total elements should always be equal to rows X columns
reshaped_array = my_array.reshape(5,5)
print(reshaped_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [36]:
# reshape() function returns a new array, so original array remains unchanged
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [37]:
# To find max and min in an array, use max() and min() function respectively.

In [38]:
my_array.max()

25

In [39]:
my_array.min()

1

In [40]:
# To find the index at which max and min number of array is present, use argmax() and argmin() function respectively

In [41]:
ran_arr = np.random.randint(1,100,10)
ran_arr

array([63, 69, 59, 76, 36, 42,  3, 27,  4, 88])

In [42]:
ran_arr.argmax()

9

In [43]:
ran_arr.argmin()

6

In [44]:
# To get the shape of the array, use .shape attribute of array. It returns a tuple

In [113]:
print(my_array.shape) # In case of 1D array, shape returns total number of elements i.e, 25 in this case
my_array

(25,)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [46]:
print(reshaped_array.shape) # Matrix of 5 X 5
reshaped_array

(5, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
# To get the data type of array, use dtype

In [48]:
my_array.dtype # 32 denotes the total bits i.e., 4 bytes

dtype('int32')

In [49]:
# If you want to use a numpy method directly, you can import it once and use it directly anywhere after that

In [50]:
from numpy.random import randint

In [51]:
randint(1,1000)

277

### NumPy Indexing and Selection

In [52]:
odds = np.arange(1,30,2)

In [53]:
odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [54]:
odds[-1] # To get the last element, we use index -1

29

In [55]:
odds[1] # For getting 1st element of array as index starts from 0

3

In [56]:
# For getting a sub-array out of array, we use slicing like what we've in lists.

In [57]:
odds[0:5] # To get array of odd numbers below 10

array([1, 3, 5, 7, 9])

In [58]:
# To get odd numbers from 11 till the end, we use:
odds[5:]

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

#### NumPy arrays differs from Python's lists in their ability to broadcast

In [59]:
my_range = np.arange(0,11)

In [60]:
my_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
my_range[0:4] = 100

In [62]:
my_range

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [63]:
# When you grab a slice from an array and assign it to a variable, it's not copied to that variable. It's just a view
# If you broadcast or change values of elements in that slice, it changes the original array also as shown below:

In [64]:
arr = np.arange(1,11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slice_of_arr = arr[0:4]

In [67]:
slice_of_arr

array([1, 2, 3, 4])

In [68]:
slice_of_arr[:] = 1000

In [69]:
slice_of_arr

array([1000, 1000, 1000, 1000])

In [70]:
# Now, check the value of array arr. It has also been changed
arr

array([1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [71]:
# If you want to create copy of array, use copy() method as show below:
arr_copy = arr.copy()

In [72]:
arr_copy

array([1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [73]:
# Now, change the value of some elements in arr_copy
arr_copy[-3:] = 0
arr_copy

array([1000, 1000, 1000, 1000,    5,    6,    7,    0,    0,    0])

In [74]:
# Check the value of arr. It shouldn't be changed
arr

array([1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [75]:
# Let's talk about indexing a 2D array

In [76]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
matrix[0][0] # Returns 5 as 1st row has index 0 and 1st column has index 0.

5

In [78]:
# To get the complete 1st row, we use index 0 as:
matrix[0]

array([ 5, 10, 15])

In [79]:
matrix[1,2] # Works fine

30

In [80]:
arr_2d = np.arange(1,21).reshape(4,5)

In [81]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [82]:
# To get number 4, we can use indexing as given below:
arr_2d[0][3]

4

In [83]:
arr_2d[1,2] # This also works fine

8

In [84]:
# Now, to grab a sub-matrix out of a matrix, we can use slicing. 
arr_2d[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [85]:
# To get a boolean array based on some condition, we can do the following:
arr_2d > 5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [86]:
arr

array([1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [87]:
bool_array = arr < 10
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
       False])

In [88]:
# Using this approach, we can do conditonal selection in 1D and 2D arrays:
arr[arr % 2 != 0]

array([5, 7, 9])

In [89]:
arr[bool_array]

array([5, 6, 7, 8, 9])

In [90]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [91]:
arr_2d[arr_2d % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### NumPy Operations
#### * Array with Array
#### * Array with Scalars
#### * Universal Array Functions

In [92]:
a1 = np.arange(0,6)
a1

array([0, 1, 2, 3, 4, 5])

In [93]:
addition = a1 + a1 # Sum of 2 arrays. In this, corresponding elements are added to each other and new array is returned

In [94]:
addition

array([ 0,  2,  4,  6,  8, 10])

In [95]:
subtraction = a1 - a1

In [96]:
subtraction # In this, corresponding elements are subtracted from each other and new array is returned

array([0, 0, 0, 0, 0, 0])

In [97]:
a1

array([0, 1, 2, 3, 4, 5])

In [98]:
square_a1 = a1 * a1

In [99]:
square_a1

array([ 0,  1,  4,  9, 16, 25])

In [100]:
# Scalar Operations on arrays 

In [101]:
a1 + 100 # Add 100 to each element of  array a1

array([100, 101, 102, 103, 104, 105])

In [102]:
# If we divide a number by 0 in NumPy, we get a warning instead of ZeroDivisionError like in Python

In [103]:
a1 / a1

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.])

In [104]:
1 / a1

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       ])

In [105]:
a1 ** 3

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [106]:
# Common array functions

In [107]:
# To get square root of every element in array
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [108]:
# To get exponent of every element in the array
np.exp(a1)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [109]:
# To get the max element in the array
np.max(a1) 

5

In [110]:
# To get sine of each element in the array
np.sin(a1) 

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [111]:
# To get log of every element in the array
np.log10(a1)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log10
  


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   ])